### ISSUE TITLE
GitPullLambda "No space left on device"

### ISSUE THREAD

**Issue by MGDMedia** [aws-quickstart/quickstart-git2s3#55]
Hello,

I'm having a hard time getting git2s3 to properly work for my GitHub repository. I've configured the Webhook through my repository settings on github.com, but GitHub is showing a 200 empty body response when I test a push.
Checking the lambda funciton logs, I see this error:

`[Errno 28] No space left on device: IOErrorTraceback (most recent call last):  File "/var/task/lambda_function.py", line 232, in lambda_handler    zipfile = zip_repo(repo_path, repo_name)  File "/var/task/lambda_function.py", line 109, in zip_repo    zf.write(os.path.join(dirname, filename), os.path.join(zdirname, filename))  File "/usr/lib64/python2.7/zipfile.py", line 1225, in write    self.fp.seek(zinfo.header_offset, 0)IOError: [Errno 28] No space left on device`

The error sounds straightforward, but I'm not understanding what device it's referring to here, and how I can go about resolving it. I understand that this is more of a question on the usage rather than an issue, but I wasn't able to find a solution in the guide or anywhere online. Any insight is greatly appreciated!

**Comment by kirankumar15** [comment]
The solution is modified to handle larger git repositories by making use of CodeBuild for performing git operations. Can you please check the new changes and deploy it and see if you are still seeing issues?
